-- 个人记账模块 PostgreSQL 建表

CREATE TABLE IF NOT EXISTS fund_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    account_no VARCHAR(64),
    type VARCHAR(20) NOT NULL,
    currency VARCHAR(3) DEFAULT 'CNY',
    balance DECIMAL(14, 2) DEFAULT 0,
    include_in_net_worth SMALLINT DEFAULT 1,
    sort_order INT DEFAULT 0,
    remark TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS acc_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    color VARCHAR(20),
    sort_order INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_acc_tag_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS acc_channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    sort_order INT DEFAULT 0,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_acc_channel_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS acc_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    parent_id BIGINT,
    type VARCHAR(10) NOT NULL,
    icon VARCHAR(50),
    budget_monthly DECIMAL(14, 2),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS acc_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(10) NOT NULL,
    amount DECIMAL(14, 2) NOT NULL,
    account_id BIGINT NOT NULL,
    target_account_id BIGINT,
    category_id BIGINT,
    trade_time TIMESTAMP NOT NULL,
    payee VARCHAR(100),
    channel_id BIGINT,
    tags VARCHAR(200),
    note TEXT,
    attachment_url VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE acc_transaction ADD COLUMN IF NOT EXISTS channel_id BIGINT;

INSERT INTO acc_channel (name, sort_order)
SELECT '微信', 1
WHERE NOT EXISTS (SELECT 1 FROM acc_channel WHERE name = '微信');

INSERT INTO acc_channel (name, sort_order)
SELECT '支付宝', 2
WHERE NOT EXISTS (SELECT 1 FROM acc_channel WHERE name = '支付宝');

INSERT INTO acc_channel (name, sort_order)
SELECT '银行卡', 3
WHERE NOT EXISTS (SELECT 1 FROM acc_channel WHERE name = '银行卡');

INSERT INTO acc_channel (name, sort_order)
SELECT '现金', 4
WHERE NOT EXISTS (SELECT 1 FROM acc_channel WHERE name = '现金');

CREATE TABLE IF NOT EXISTS investment_symbol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,
    market VARCHAR(20),
    currency VARCHAR(3) DEFAULT 'CNY',
    current_price DECIMAL(14, 4),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS investment_trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol_id BIGINT NOT NULL,
    trade_type VARCHAR(20) NOT NULL,
    quantity DECIMAL(18, 6),
    price DECIMAL(14, 4),
    amount DECIMAL(14, 2) NOT NULL,
    fee DECIMAL(14, 2) DEFAULT 0,
    trade_time TIMESTAMP NOT NULL,
    account_id BIGINT,
    note TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO acc_category (name, parent_id, type, icon, budget_monthly)
SELECT '餐饮', NULL, 'expense', 'cutlery', 2000
WHERE NOT EXISTS (SELECT 1 FROM acc_category WHERE name = '餐饮' AND type = 'expense');

INSERT INTO acc_category (name, parent_id, type, icon, budget_monthly)
SELECT '交通', NULL, 'expense', 'car', 600
WHERE NOT EXISTS (SELECT 1 FROM acc_category WHERE name = '交通' AND type = 'expense');

INSERT INTO acc_category (name, parent_id, type, icon, budget_monthly)
SELECT '购物', NULL, 'expense', 'shopping', 1500
WHERE NOT EXISTS (SELECT 1 FROM acc_category WHERE name = '购物' AND type = 'expense');

INSERT INTO acc_category (name, parent_id, type, icon, budget_monthly)
SELECT '居住', NULL, 'expense', 'home', 3000
WHERE NOT EXISTS (SELECT 1 FROM acc_category WHERE name = '居住' AND type = 'expense');

INSERT INTO acc_category (name, parent_id, type, icon, budget_monthly)
SELECT '娱乐', NULL, 'expense', 'game', 500
WHERE NOT EXISTS (SELECT 1 FROM acc_category WHERE name = '娱乐' AND type = 'expense');

INSERT INTO acc_category (name, parent_id, type, icon)
SELECT '工资', NULL, 'income', 'money'
WHERE NOT EXISTS (SELECT 1 FROM acc_category WHERE name = '工资' AND type = 'income');

INSERT INTO acc_category (name, parent_id, type, icon)
SELECT '其他收入', NULL, 'income', 'gift'
WHERE NOT EXISTS (SELECT 1 FROM acc_category WHERE name = '其他收入' AND type = 'income');
